using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YellowstonePathology.Business.Persistence
{
    public class PersistentPrimaryKeyProperty : System.Attribute
    {
        bool m_IsAutoGenerated;

        public PersistentPrimaryKeyProperty(bool isAutoGenerated)
        {
            this.m_IsAutoGenerated = isAutoGenerated;
        }

        public bool IsAutoGenerated
        {
            get { return this.m_IsAutoGenerated; }
        }
    }
}

