using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace YellowstonePathology.Business.Test.Model
{
    public class VentanaStainCollection : ObservableCollection<VentanaStain>
    {        
        public VentanaStainCollection()
        {
            this.Add(new VentanaStain("1", "GMS II", "106", "Block", "Default"));
            this.Add(new VentanaStain("2", "Mucicarmine", "123", "Block", "Default"));
            this.Add(new VentanaStain("3", "D K/L-Titration", "IGKIGL", "Block", "Default"));
            this.Add(new VentanaStain("3", "Retic", "151", "Block", "Default"));
            this.Add(new VentanaStain("4", "Mucicarmine Dark", "123", "Block", "Brown"));
            this.Add(new VentanaStain("5", "TRYPTASE Titration", "353", "Block", "Default"));
            this.Add(new VentanaStain("5", "W-GMS II", "106", "Fluid", "Default"));
            this.Add(new VentanaStain("6", "D KI-67/MART1", "KI67MA", "Block", "Default"));
            this.Add(new VentanaStain("7", "R HMB-45", "111", "Block", "Red"));
            this.Add(new VentanaStain("8", "D T PAX 5/ZAP 70", "PAX5ZP70", "Block", "Default"));
            this.Add(new VentanaStain("10", "D CK34/T-P504S", "CK34P504RM", "Block", "Default"));
            this.Add(new VentanaStain("17", "R    S100 TITRAT", "152", "Block", "Red"));
            this.Add(new VentanaStain("18", "R Hpylori Titration", "107", "Block", "Red"));
            this.Add(new VentanaStain("21", "R MART-1", "119", "Block", "Red"));
            this.Add(new VentanaStain("22", "R MITF/Titration", "178", "Block", "Red"));
            this.Add(new VentanaStain("23", "R P504S TITRATE", "133", "Block", "Red"));
            this.Add(new VentanaStain("24", "D TTF1/NAPSIN A", "TTFNPSNA", "Block", "Default"));
            this.Add(new VentanaStain("31", "R SOX-10", "356", "Block", "Red"));
            this.Add(new VentanaStain("32", "W-R SOX-10", "356", "Fluid", "Default"));
            this.Add(new VentanaStain("214", "BCL-6 TITRATION", "57", "Block", "Default"));
            this.Add(new VentanaStain("215", "NKX3.1 Titration", "355", "Block", "Default"));
            this.Add(new VentanaStain("216", "D2-40 TITRATE", "224", "Block", "Default"));
            this.Add(new VentanaStain("217", "SATB2 TITRATION", "357", "Block", "Default"));
            this.Add(new VentanaStain("219", "W-SATB2-T", "357", "Fluid", "Default"));
            this.Add(new VentanaStain("220", "PMS2 - Titration", "217", "Block", "Default"));
            this.Add(new VentanaStain("222", "CD31", "176", "Block", "Default"));
            this.Add(new VentanaStain("223", "BCL-2 TITRATION", "56", "Block", "Default"));
            this.Add(new VentanaStain("224", "WCD31", "176", "Fluid", "Default"));
            this.Add(new VentanaStain("225", "HSA Titration", "197", "Block", "Default"));
            this.Add(new VentanaStain("226", "W/NapsinA-T", "270", "Fluid", "Default"));
            this.Add(new VentanaStain("227", "Glypican 3 Titration", "276", "Block", "Default"));
            this.Add(new VentanaStain("228", "DOG-1Titration", "298", "Block", "Default"));
            this.Add(new VentanaStain("229", "W / Glypican 3 Titration", "276", "Block", "Default"));
            this.Add(new VentanaStain("239", "CD8 Titration", "80", "Block", "Default"));
            this.Add(new VentanaStain("240", "W/CD8 - T", "80", "Fluid", "Default"));
            this.Add(new VentanaStain("244", "Calretinin Titration", "60", "Block", "Default"));
            this.Add(new VentanaStain("245", "W/Calret-T", "60", "Fluid", "Default"));
            this.Add(new VentanaStain("246", "WT1", "173", "Block", "Default"));
            this.Add(new VentanaStain("249", "D CD3-T/CD20", "CD3CD20", "Block", "Default"));
            this.Add(new VentanaStain("250", "CA19-9", "59", "Block", "Default"));
            this.Add(new VentanaStain("251", "BCA-225", "55", "Block", "Default"));
            this.Add(new VentanaStain("252", "W/CA19-9", "59", "Fluid", "Default"));
            this.Add(new VentanaStain("253", "D CD3/CD20W/T", "CD3CD20", "Block", "Default"));
            this.Add(new VentanaStain("258", "E-cadherin", "94", "Block", "Default"));
            this.Add(new VentanaStain("259", "ER TITRATION", "98", "Block", "Default"));
            this.Add(new VentanaStain("261", "CDX2 TITRATION", "81", "Block", "Default"));
            this.Add(new VentanaStain("262", "W-CDX2-T", "81", "Fluid", "Default"));
            this.Add(new VentanaStain("264", "CD23 Titration", "66", "Block", "Default"));
            this.Add(new VentanaStain("265", "PR TITRATION", "144", "Block", "Default"));
            this.Add(new VentanaStain("267", "Beta-Catenin", "299", "Block", "Default"));
            this.Add(new VentanaStain("269", "CD56 Titration", "77", "Block", "Default"));
            this.Add(new VentanaStain("271", "CD138", "273", "Block", "Default"));
            this.Add(new VentanaStain("273", "CD68 titration", "78", "Block", "Default"));
            this.Add(new VentanaStain("276", "W/ CK 5/6", "89", "Fluid", "Default"));
            this.Add(new VentanaStain("277", "CK34 BE 12", "88", "Block", "Default"));
            this.Add(new VentanaStain("280", "W/ER", "98", "Fluid", "Default"));
            this.Add(new VentanaStain("281", "W/PR", "144", "Fluid", "Default"));
            this.Add(new VentanaStain("282", "CK7 Titration", "90", "Block", "Default"));
            this.Add(new VentanaStain("283", "CK5/6 Titration", "89", "Block", "Default"));
            this.Add(new VentanaStain("284", "BROWN-HMB-45", "111", "Block", "Brown"));
            this.Add(new VentanaStain("285", "Ki67", "116", "Block", "Default"));
            this.Add(new VentanaStain("286", "Chromo Titration", "83", "Block", "Default"));
            this.Add(new VentanaStain("287", "W/CK5/6 Titration", "89", "Fluid", "Default"));
            this.Add(new VentanaStain("288", "W/CK 7 - T", "90", "Fluid", "Default"));
            this.Add(new VentanaStain("289", "P53 Titration", "134", "Block", "Default"));
            this.Add(new VentanaStain("290", "Cyclin D1 Titration", "85", "Block", "Default"));
            this.Add(new VentanaStain("291", "W-Ki67", "116", "Fluid", "Default"));
            this.Add(new VentanaStain("292", "W/CD56-T", "77", "Fluid", "Default"));
            this.Add(new VentanaStain("293", "W/TdT - T", "157", "Fluid", "Default"));
            this.Add(new VentanaStain("294", "S100 Titration", "152", "Block", "Default"));
            this.Add(new VentanaStain("295", "SMM Titration", "154", "Block", "Default"));
            this.Add(new VentanaStain("296", "W/S100-T", "152", "Fluid", "Default"));
            this.Add(new VentanaStain("297", "Synap Titration", "156", "Block", "Default"));
            this.Add(new VentanaStain("298", "W-SMM Titration", "154", "Fluid", "Default"));
            this.Add(new VentanaStain("299", "CMV Titration", "350", "Block", "Default"));
            this.Add(new VentanaStain("301", "RCC Titration", "149", "Block", "Default"));
            this.Add(new VentanaStain("302", "W/CD 5-T", "75", "Fluid", "Default"));
            this.Add(new VentanaStain("303", "W/P53 Titration", "134", "Fluid", "Default"));
            this.Add(new VentanaStain("304", "CD5 Titration", "75", "Block", "Default"));
            this.Add(new VentanaStain("305", "TdT Titration", "157", "Block", "Default"));
            this.Add(new VentanaStain("306", "SMA Titration", "153", "Block", "Default"));
            this.Add(new VentanaStain("311", "P63", "135", "Block", "Default"));
            this.Add(new VentanaStain("312", "Desmin", "92", "Block", "Default"));
            this.Add(new VentanaStain("313", "W/P63", "135", "Fluid", "Default"));
            this.Add(new VentanaStain("314", "W/CD68-T", "78", "Fluid", "Default"));
            this.Add(new VentanaStain("315", "Napsin A - Titration", "270", "Block", "Default"));
            this.Add(new VentanaStain("316", "Zap-70 Titration", "165", "Block", "Default"));
            this.Add(new VentanaStain("318", "CD45 (LCA) Titration", "73", "Block", "Default"));
            this.Add(new VentanaStain("319", "W/BCA-225", "55", "Fluid", "Default"));
            this.Add(new VentanaStain("320", "W/CD45 (LCA) Titration", "73", "Fluid", "Default"));
            this.Add(new VentanaStain("332", "MSA Titration", "125", "Block", "Default"));
            this.Add(new VentanaStain("339", "W/Zap 70 - T", "165", "Fluid", "Default"));
            this.Add(new VentanaStain("361", "W/CD19-T", "172", "Fluid", "Default"));
            this.Add(new VentanaStain("362", "Hpylori Titration", "107", "Block", "Default"));
            this.Add(new VentanaStain("363", "CD19 TITRATION", "172", "Block", "Default"));
            this.Add(new VentanaStain("364", "W/Hpylori-T", "107", "Fluid", "Default"));
            this.Add(new VentanaStain("368", "W / HSA Titration", "197", "Fluid", "Default"));
            this.Add(new VentanaStain("436", "W/CD34", "70", "Fluid", "Default"));
            this.Add(new VentanaStain("601", "Alcian Blue", "51", "Block", "Default"));
            this.Add(new VentanaStain("602", "PAS - Alcian Blue", "138", "Block", "Default"));
            this.Add(new VentanaStain("607", "Elastic Stain", "96", "Block", "Default"));
            this.Add(new VentanaStain("608", "Giemsa Stain", "105", "Block", "Default"));
            this.Add(new VentanaStain("617", "Congo Red", "84", "Block", "Default"));
            this.Add(new VentanaStain("643", "Iron NFR Dark", "115", "Block", "Brown"));
            this.Add(new VentanaStain("644", "W-Iron NFR Dark", "115", "Fluid", "Brown"));
            this.Add(new VentanaStain("654", "PAS-F", "139", "Block", "Default"));
            this.Add(new VentanaStain("655", "W PAS-F", "139", "Fluid", "Default"));
            this.Add(new VentanaStain("656", "PAS-D", "140", "Block", "Default"));
            this.Add(new VentanaStain("657", "PAS", "137", "Block", "Default"));
            this.Add(new VentanaStain("676", "Trichrome III", "160", "Block", "Default"));
            this.Add(new VentanaStain("706", "Steiner", "155", "Block", "Default"));
            this.Add(new VentanaStain("707", "Steiner WET", "155", "Fluid", "Default"));
            this.Add(new VentanaStain("709", "AFB III", "50", "Block", "Default"));
            this.Add(new VentanaStain("861", "W/GATA-3 Titration", "346", "Fluid", "Default"));
            this.Add(new VentanaStain("901", "OSCAR TITRAT", "170", "Block", "Default"));
            this.Add(new VentanaStain("903", "W/CD10", "61", "Fluid", "Default"));
            this.Add(new VentanaStain("904", "W/CD3-T", "68", "Fluid", "Default"));
            this.Add(new VentanaStain("907", "W/OSCAR-T", "170", "Fluid", "Default"));
            this.Add(new VentanaStain("908", "Ber-EP4", "216", "Block", "Default"));
            this.Add(new VentanaStain("909", "BROWN - MITF", "178", "Block", "Brown"));
            this.Add(new VentanaStain("910", "BROWN-SOX10", "356", "Block", "Brown"));
            this.Add(new VentanaStain("911", "CD10 TITRATE", "61", "Block", "Default"));
            this.Add(new VentanaStain("912", "W-BROWN-SOX10", "356", "Fluid", "Brown"));
            this.Add(new VentanaStain("914", "CD15 TITRATION", "64", "Block", "Default"));
            this.Add(new VentanaStain("916", "W/CEA-T", "82", "Fluid", "Default"));
            this.Add(new VentanaStain("918", "CEA Titration", "82", "Block", "Default"));
            this.Add(new VentanaStain("919", "MOC31 TITRATE", "215", "Block", "Default"));
            this.Add(new VentanaStain("921", "CA-125 Titration", "58", "Block", "Default"));
            this.Add(new VentanaStain("922", "W/CA-125 Titration", "58", "Fluid", "Default"));
            this.Add(new VentanaStain("925", "FXIIIa Titration", "101", "Block", "Default"));
            this.Add(new VentanaStain("927", "CD25", "67", "Block", "Default"));
            this.Add(new VentanaStain("929", "CK20 Titration", "87", "Block", "Default"));
            this.Add(new VentanaStain("931", "BROWN-MART 1", "119", "Block", "Brown"));
            this.Add(new VentanaStain("933", "CD99 Titration", "177", "Block", "Default"));
            this.Add(new VentanaStain("934", "W/CK20-T", "87", "Fluid", "Default"));
            this.Add(new VentanaStain("936", "CD117 titration", "62", "Block", "Default"));
            this.Add(new VentanaStain("937", "W/MOC31-T", "215", "Fluid", "Default"));
            this.Add(new VentanaStain("938", "CD30", "69", "Block", "Default"));
            this.Add(new VentanaStain("939", "W-CD117", "62", "Fluid", "Default"));
            this.Add(new VentanaStain("940", "PAX5 TITRATION", "141", "Block", "Default"));
            this.Add(new VentanaStain("941", "W-PAX5 TITRATION", "141", "Fluid", "Default"));
            this.Add(new VentanaStain("944", "W/CD79a-T", "79", "Fluid", "Default"));
            this.Add(new VentanaStain("945", "CD7 Titration", "180", "Block", "Default"));
            this.Add(new VentanaStain("947", "CD79a Titration", "79", "Block", "Default"));
            this.Add(new VentanaStain("948", "EMA Titration", "97", "Block", "Default"));
            this.Add(new VentanaStain("949", "W/CD 7-T", "180", "Fluid", "Default"));
            this.Add(new VentanaStain("951", "W/CK 8/18-T", "91", "Fluid", "Default"));
            this.Add(new VentanaStain("954", "W/PanKer-T", "136", "Fluid", "Default"));
            this.Add(new VentanaStain("955", "W/CD20-T", "65", "Fluid", "Default"));
            this.Add(new VentanaStain("957", "Mammaglobin", "118", "Block", "Default"));
            this.Add(new VentanaStain("958", "W/GCDFP-15", "103", "Fluid", "Default"));
            this.Add(new VentanaStain("959", "Fascin", "102", "Block", "Default"));
            this.Add(new VentanaStain("960", "Thyro Titration", "158", "Block", "Default"));
            this.Add(new VentanaStain("961", "W/Thyro Titration", "158", "Fluid", "Default"));
            this.Add(new VentanaStain("962", "W/Mammaglobin", "118", "Fluid", "Default"));
            this.Add(new VentanaStain("963", "CD20 Titration", "65", "Block", "Default"));
            this.Add(new VentanaStain("964", "CD34", "70", "Block", "Default"));
            this.Add(new VentanaStain("965", "GCDFP-15  Titration", "103", "Block", "Default"));
            this.Add(new VentanaStain("966", "PAX8 Titration", "253", "Block", "Default"));
            this.Add(new VentanaStain("967", "Panker Titration", "136", "Block", "Default"));
            this.Add(new VentanaStain("969", "Vim Titration", "164", "Block", "Default"));
            this.Add(new VentanaStain("970", "MSH-2 Titration", "122", "Block", "Default"));
            this.Add(new VentanaStain("974", "Myelop Titration", "126", "Block", "Default"));
            this.Add(new VentanaStain("979", "MSH6 Titraion", "218", "Block", "Default"));
            this.Add(new VentanaStain("982", "GATA-3 Titration", "346", "Block", "Default"));
            this.Add(new VentanaStain("983", "CD3 Titration", "68", "Block", "Default"));
            this.Add(new VentanaStain("984", "W/Villin - T", "163", "Fluid", "Default"));
            this.Add(new VentanaStain("985", "W/TTF 1 - T", "161", "Fluid", "Default"));
            this.Add(new VentanaStain("986", "CK17 TITRATE", "86", "Block", "Default"));
            this.Add(new VentanaStain("988", "P504s - T", "133", "Block", "Default"));
            this.Add(new VentanaStain("990", "CD4 TITRATE", "71", "Block", "Default"));
            this.Add(new VentanaStain("991", "GFAP Titration", "104", "Block", "Default"));
            this.Add(new VentanaStain("994", "P16", "132", "Block", "Default"));
            this.Add(new VentanaStain("995", "W/P16 TITRATE", "132", "Fluid", "Default"));
            this.Add(new VentanaStain("996", "W / GATA-3 Titration", "346", "Fluid", "Default"));
            this.Add(new VentanaStain("998", "W/P504s - T", "133", "Fluid", "Default"));
            this.Add(new VentanaStain("999", "W-NKX3.1-T", "355", "Fluid", "Default"));
            this.Add(new VentanaStain("1000", "Kappa Titration", "113", "Block", "Default"));
            this.Add(new VentanaStain("1001", "Lambda Titration", "114", "Block", "Default"));
            this.Add(new VentanaStain("1002", "TTF1 Titration", "161", "Block", "Default"));
            this.Add(new VentanaStain("1003", "PLAP Titration", "142", "Block", "Default"));
            this.Add(new VentanaStain("1004", "W/CD 4-T", "71", "Fluid", "Default"));
            this.Add(new VentanaStain("1006", "MLH1 Titration", "121", "Block", "Default"));
        }

        public VentanaStain GetByYPITestId(string ypiTestId)
        {
            VentanaStain result = null;
            foreach(VentanaStain item in this)
            {
                if(item.YPIId == ypiTestId)
                {
                    result = item;
                    break;
                }
            }
            return result;
        }
    }
}
