using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YellowstonePathology.Business.Persistence
{
    public class PersistentPrimaryKeyProperty : System.Attribute
    {
        bool m_IsAutoGenerated;
        private int m_MaxLength;

        public PersistentPrimaryKeyProperty(bool isAutoGenerated, int maxLength)
        {
            this.m_IsAutoGenerated = isAutoGenerated;
            this.m_MaxLength = maxLength;
        }

        public bool IsAutoGenerated
        {
            get { return this.m_IsAutoGenerated; }
        }

        public int MaxLength
        {
            get { return this.m_MaxLength; }
        }
    }
}

