//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellowstonePathology.Business.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TheNewApplicationIsLive {
            get {
                return ((bool)(this["TheNewApplicationIsLive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TestSQL;Initial Catalog=YPIData;Integrated Security=True")]
        public string ProductionConnectionString {
            get {
                return ((string)(this["ProductionConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=development\\develop;Initial Catalog=YPIData;Integrated Security=True")]
        public string TestConnectionString {
            get {
                return ((string)(this["TestConnectionString"]));
            }
            set {
                this["TestConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Development\\Develop;Initial Catalog=YPIData;Integrated Security=True")]
        public string DevelopConnectionString {
            get {
                return ((string)(this["DevelopConnectionString"]));
            }
            set {
                this["DevelopConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TestSQL;Initial Catalog=YPIData;Integrated Security=True")]
        public string CurrentConnectionString {
            get {
                return ((string)(this["CurrentConnectionString"]));
            }
            set {
                this["CurrentConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("changedb")]
        public string ChangeDBPassword {
            get {
                return ((string)(this["ChangeDBPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Yellowstone Pathology Institute\\Dictation\\")]
        public string LocalDictationFolder {
            get {
                return ((string)(this["LocalDictationFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cfileserver\\documents\\Dictation\\")]
        public string ServerDictationFolder {
            get {
                return ((string)(this["ServerDictationFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Yellowstone Pathology Institute\\Dictation\\Done\\")]
        public string LocalDoneDictationFolder {
            get {
                return ((string)(this["LocalDoneDictationFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\LIS;Initial Catalog=YPILocalData;Integrated Security=True")]
        public string LocalDataConnectionString {
            get {
                return ((string)(this["LocalDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Yellowstone Pathology Institute\\")]
        public string LocalApplicationFolder {
            get {
                return ((string)(this["LocalApplicationFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LocalSettings.xml")]
        public string LocalSettingsFile {
            get {
                return ((string)(this["LocalSettingsFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.93.39.100\\ChannelData\\Incoming\\1000")]
        public string HL7IncomingChannelPath {
            get {
                return ((string)(this["HL7IncomingChannelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.93.39.100\\ChannelData\\Outgoing")]
        public string HL7OutgoingChannelPath {
            get {
                return ((string)(this["HL7OutgoingChannelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Yellowstone Pathology Institute\\ClientMissingInformationLetter.d" +
            "oc")]
        public string ClientMissingInformationLetterFileName {
            get {
                return ((string)(this["ClientMissingInformationLetterFileName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3/9/2010")]
        public string LastLocalDataUpdate {
            get {
                return ((string)(this["LastLocalDataUpdate"]));
            }
            set {
                this["LastLocalDataUpdate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cfileserver\\Documents\\SpecimenLog\\")]
        public string SpecimenLogScannedDocumentFilePath {
            get {
                return ((string)(this["SpecimenLogScannedDocumentFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL1;Failover Partner=SQL2;Initial Catalog=YPIData;Integrated Securit" +
            "y=True;")]
        public string MirroredConnectionString {
            get {
                return ((string)(this["MirroredConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Thermo Scientific\\LabWriter V2.2\\Cache")]
        public string SlideMateCachePath {
            get {
                return ((string)(this["SlideMateCachePath"]));
            }
            set {
                this["SlideMateCachePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Server=testsql;database=ypidata; Integrated Security=SSPI")]
        public string ServerSqlXmlConnectionString {
            get {
                return ((string)(this["ServerSqlXmlConnectionString"]));
            }
            set {
                this["ServerSqlXmlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Server=.\\lis;database=ypilocaldata; Integrated Security=SSPI")]
        public string LocalSqlXmlConnectionString {
            get {
                return ((string)(this["LocalSqlXmlConnectionString"]));
            }
            set {
                this["LocalSqlXmlConnectionString"] = value;
            }
        }
    }
}
