//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellowstonePathology.Business.Domain.Persistence.SqlXmlPersistence.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Server=testsql;database=ypidata; Integrated Security=SSPI")]
        public string SqlXmlConnectionString {
            get {
                return ((string)(this["SqlXmlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TestSQL;Initial Catalog=YPIData;Integrated Security=True")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Server=.\\lis;database=ypilocaldata; Integrated Security=SSPI")]
        public string LocalSqlXmlConnectionString {
            get {
                return ((string)(this["LocalSqlXmlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\LIS;Initial Catalog=YPILocalData;Integrated Security=True")]
        public string LocalSqlConnectionString {
            get {
                return ((string)(this["LocalSqlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Server=development\\develop;database=ypidata; Integrated Securit" +
            "y=SSPI")]
        public string TestSqlXmlConnectionString {
            get {
                return ((string)(this["TestSqlXmlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=development\\develop;Initial Catalog=YPIData;Integrated Security=True")]
        public string TestSqlConnectionString {
            get {
                return ((string)(this["TestSqlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Server=testsql;database=ypicube; Integrated Security=SSPI")]
        public string CubeSqlXmlConnectionString {
            get {
                return ((string)(this["CubeSqlXmlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TestSQL;Initial Catalog=YPICube;Integrated Security=True")]
        public string CubeSqlConnectionString {
            get {
                return ((string)(this["CubeSqlConnectionString"]));
            }
        }
    }
}
